---
title             : "Maternal Emotion Dysregulation and its Association with Child Internalizing and     Externalizing Behaviors and Heart Rate Variability"
shorttitle        : "Maternal Emotion Dysregulation and Child Outcomes"

author: 
  - name          : "Jackie O'Brien"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Jenn Lewis"
    affiliation   : "1"
  - name          : "Yoel Everett"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"

authornote: 
  



abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "emotion regulation, parenting, child outcomes"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup,  include=FALSE}
#You will need to install kableExtra package in order for this to run
#You will need to install jtools package in order for this to run
#Load Packages
library("papaja")
library(tidyverse)
library(rio)
library(here)
library(kableExtra)
library(jtools)
library(knitr)

knitr::opts_chunk$set()
```

```{r tidy data}
#import data and clean names
data <- import(here("data", "R Project Data copy.xlsx")) %>%
  janitor::clean_names()

#view data
#glimpse(data)


#tidy data using required functions
tidy_data <- data %>%
  filter(!is.na(family_id)) %>%
  gather(text, val, 2:3) %>%
  separate(text, c("text", "type"), sep= "_") %>%
  spread(type, val) %>%
  select(-text)

tidy_data <- data %>%
  filter(!is.na(family_id)) %>%
  gather(key = var, value = cbcl_score, starts_with("cbcl")) %>% 
  separate(var, 
           c("discard", "cbcl_subtype"), 
           sep = "_",
           convert = TRUE) %>%
  select(-discard) 

#view tidy data
#glimpse(tidy_data)

#Center DERS and Reactivity variables
center_scale <- function(x) {
  as.numeric(scale(x, scale = FALSE))
}

#Create Reactivity Variable
tidy_data <- tidy_data %>% 
  mutate(reactivity = child_lego - child_baseline, 
         ders_c = center_scale(ders), 
         reactivity_c = center_scale(reactivity))

#glimpse(tidy_data)
```

#Introduction

# Methods

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.

# Results

```{r descriptives ders and reactivity, results='asis'}
#str(tidy_data)

#Descriptives Table DERS and Reactivity
table_ders_reactivity <- tidy_data %>% 
  summarize(DERS_mean = mean(ders, na.rm = TRUE), 
            DERS_SD = sd(ders, na.rm = TRUE), 
            Reactivity_mean = mean(reactivity, na.rm = TRUE), 
            Reactivity_SD = sd(reactivity, na.rm = TRUE))

table_ders_reactivity[, -1] <-printnum(table_ders_reactivity[, -1])

apa_table(table_ders_reactivity,
          caption = "Means and SDs for Maternal Emotion Dysregulation (DERS) and Child Reactivity")

#kable(table, 
#      format = "latex",
#      booktabs = TRUE,
#      caption = "Means and SDs of maternal emotion dysregulation (DERS) and child reactivity")

```

```{r descriptives cbcl, results='asis'}
#Descriptives Table Internalizing and Externalizing Behavior
table_cbcl <- tidy_data %>%
  group_by(cbcl_subtype) %>%
  summarize(cbcl_mean= round(mean(cbcl_score, na.rm = TRUE), 2), 
            cbcl_SD = sd(cbcl_score, na.rm = TRUE))

table_cbcl[, -1] <-printnum(table_cbcl[, -1])

apa_table(table_cbcl,
          caption = "Means and SDs for Child Internalizing and Externalizing Behavior")


#kable(table2, 
 #     format = "latex",
  #    booktabs = TRUE,
  #    caption = "Means and SDs of child internalizing and externalizing behavior")

```

```{r linear regression internalizing, echo=FALSE, results='asis'}
linear_model1 <- lm(cbcl_score ~ ders_c * reactivity_c, 
                    data = subset(tidy_data, cbcl_subtype == "int"))
#summary(linear_model1)

linear_model1_print <- apa_print(linear_model1)

apa_table(linear_model1_print$table,
          caption = "Results of Linear Regression Predicting Child Internalizing Behavior")

#Tried this code from sjPlot package, but it will not knit to pdf
#tab_model(
# linear_model1,
#  pred.labels = c("Intercept", "Maternal Em. Dysreg", "Child Reactivity", "Interaction"),
#  dv.labels = c("Internalizing Behavior (CBCL)"),
#  string.pred = "Coefficient",
#  string.ci = "CI (95%)",
#  string.p = "P-Value"
#  )
```

```{r linear regression externalizing, echo=FALSE, results='asis'}
linear_model2 <- lm(cbcl_score ~ ders_c * reactivity_c, 
                    data = subset(tidy_data, cbcl_subtype == "ext"))

linear_model2_print <- apa_print(linear_model2)

apa_table(linear_model2_print$table,
          caption = "Results of Linear Regression Predicting Child Externalizing Behavior")

#summary(linear_model2)

#stargazer(linear_model2, type = "text", title = "Linear Model 2", digits = 2)

#library(sjPlot)
#tab_model(
#  linear_model2,
#  pred.labels = c("Intercept", "Maternal Em. Dysreg", "Child Reactivity", "Interaction"),
#  dv.labels = c("Externalizing Behavior (CBCL)"),
#  string.pred = "Coefficient",
#  string.ci = "CI (95%)",
#  string.p = "P-Value"
#  )
```


```{r plot1, fig.cap="Maternal Emotion Dysregulation and Child Behaviors"}
#A scatterplot of maternal emotion dysregulation (x-axis)
#and child behaviors (y-axis), including a regression line 
ggplot(tidy_data, aes(x=ders, y=cbcl_score, color = cbcl_subtype)) +
  geom_point(color="black") +
  geom_smooth(method = "lm") +
   labs(x="Maternal Emotion Dysregulation (DERS)",
       y="Child Problem Behaviors")
```

```{r plot2, fig.cap="Maternal Emotion Dysregulation and Child HRV Reactivity"}
#A scatterplot of maternal emotion dysregulation (x-axis)
#and reactivity (y-axis), including a regression line 
ggplot(tidy_data, aes(x=ders, y=reactivity)) +
  geom_point(color="black") +
  geom_smooth(method = "lm") +
   labs(x="Maternal Emotion Dysregulation (DERS)",
       y="Child Reactivity HRV")
```

```{r plot3, fig.cap= "Child Reactivity Predicting Child Behavior Problems at Three Different Levels of Maternal Emotion Dysregulation "}
interaction_plot <- interact_plot(linear_model1, pred = "reactivity_c", modx = "ders_c", centered = "none", 
      x.label="Child Reactivity HRV",
      y.label="Child Behavior Problems (CBCL)",
      legend.main = "DERS")
interaction_plot
```



# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
